### PR TITLE
Update replicating-fama-and-french-factors.qmd

### PR DESCRIPTION
**Pull request by JiaZhang42**
- independent sorting in ff3
- number of portfolios to construct ff5 size factor

### CODE REVIEW

**Comment by JiaZhang42** [comment]
I accidentally clicked the merge button. My intention was to submit the pull request for review. Apologies!

**Comment by christophscheuch** [comment]
Thank you for your PR. I tagged @patrick-weiss as a reviewer. If he approves, we have to adapt the Python version as well.

**Review by patrick-weiss — APPROVED** [review]
Very good catches. The code is correct! However, the text is not.

**Review by JiaZhang42 — COMMENTED** [review]
Exactly! Thanks.
The Python version was correct about "independent sort" in the text though.🤣

**Comment by patrick-weiss** [comment]
I was just correcting that again while trying to rephrase the sentence. I initially only wanted to paste your comments and then make my changes. Well, too slow.

**Pull request merged**
